# Указание версии
version: "3.5"

# Объявление переменных окружения
x-environment:
  &default-back-environment
  # Database settings
  POSTGRES_DB: taiga
  POSTGRES_USER: taiga
  POSTGRES_PASSWORD: taiga
  POSTGRES_HOST: taiga-db
  # Taiga settings
  TAIGA_SECRET_KEY: "buchakucha"
  TAIGA_SITES_DOMAIN: "192.168.1.106:9000"
  TAIGA_SITES_SCHEME: "http"
  # Email settings. Uncomment following lines and configure your SMTP server
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  DEFAULT_FROM_EMAIL: "no-reply@example.com"
  EMAIL_USE_TLS: "False"
  EMAIL_USE_SSL: "False"
  EMAIL_HOST: "smtp.host.example.com"
  EMAIL_PORT: 587
  EMAIL_HOST_USER: "user"
  EMAIL_HOST_PASSWORD: "password"
  # Rabbitmq settings
  # Should be the same as in taiga-async-rabbitmq and taiga-events-rabbitmq
  RABBITMQ_USER: taiga
  RABBITMQ_PASS: taiga
  # Telemetry settings
  ENABLE_TELEMETRY: "False"

# Указание томов (связывание файлов на машине и в контейнере)
x-volumes:
  &default-back-volumes
  - ./taiga-docker/data/taiga-static-data:/taiga-back/static
  - ./taiga-docker/data/taiga-media-data:/taiga-back/media

# Объявление сервисов
services:
  # Настройка сервисов Taiga
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
    volumes:
      - ./taiga-docker/data/taiga-db-data:/var/lib/postgresql/data
    # Указание сети 
    networks:
      - taiga

  taiga-back:
    image: taigaio/taiga-back:6.0.9
    environment:
      <<: *default-back-environment
      PUBLIC_REGISTER_ENABLED: "True"
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq

  taiga-async:
    image: taigaio/taiga-back:6.0.9
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-back
      - taiga-async-rabbitmq

  taiga-async-rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - ./taiga-docker/data/taiga-async-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-front:
    image: taigaio/taiga-front:6.0.10
    environment:
      PUBLIC_REGISTER_ENABLED: "true"
      TAIGA_URL: "http://192.168.1.106:9000"
      TAIGA_WEBSOCKETS_URL: "ws://192.168.1.106:9000"
    networks:
      - taiga
    # volumes:
    #   - ./conf.json:/usr/share/nginx/html/conf.json

  taiga-events:
    image: taigaio/taiga-events:6.0.2
    environment:
      RABBITMQ_USER: taiga
      RABBITMQ_PASS: taiga
      TAIGA_SECRET_KEY: "buchakucha"
    networks:
      - taiga
    depends_on:
      - taiga-events-rabbitmq

  taiga-events-rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - ./taiga-docker/data/taiga-events-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-protected:
    image: taigaio/taiga-protected:6.0.0
    environment:
      MAX_AGE: 360
      SECRET_KEY: "buchakucha"
    networks:
      - taiga

  taiga-gateway:
    image: nginx:1.19-alpine
    ports:
      - "9000:80"
    volumes:
      - ./taiga-docker/taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - ./taiga-docker/data/taiga-static-data:/taiga/static
      - ./taiga-docker/data/taiga-media-data:/taiga/media
    networks:
      - taiga
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events

volumes:
  taiga-static-data:
  taiga-media-data:
  taiga-db-data:
  taiga-async-rabbitmq-data:
  taiga-events-rabbitmq-data:

networks:
  taiga: